### ISSUE TITLE
Feature addition

### ISSUE THREAD

**Issue by me0ne0** [leovan/SciHubEVA#19]
1) good to have proxychains mechanism for auto switching to different proxies.

2) can captcha be bypassed? https://github.com/bibcure/scihub2pdf did it. worked for me for sometime.

3) add support for arxiv.

4) good to have doi numbers printed of docs, which failed to download. e.g like in log file.

**Comment by leovan** [comment]
1. I am not sure what is proxychains? If you mean changing proxy server automatically when you have many available proxy servers, I think it won't be done in this tool. You may need a proxy client which support it.
2. Now captcha is downloaded with same setting of pdf, if you set a proxy server, it will also download captcha with it.
3. Since arxiv is an open access host for articles, it won't be included in this tool. Also this tool names "SciHubEVA", thus it will only support sci-hub now.
4. I am not sure what do you mean? If you want to add a DOI or PMID file name keywords supported, please refer [#17](https://github.com/leovan/SciHubEVA/issues/17), will be done in next release.

**Comment by me0ne0** [comment]
ok. so i will close this thread now. thank you for your reply.
